<?php
/**
 * Created by PhpStorm.
 * User: wangyibo
 * Date: 2016-11-19
 * Time: 20:56
 */

namespace BuildInfo\crawler;

use RedisClient\RedisClient;
use RedisClient\ClientFactory;

class AnQuanPingJiaShiCrawler extends BaseCrawler
{
    public $bodyQuery;
    public $page = 1;
    protected $companyCollection;
    protected $limit = 1;

    function __construct($urlRaw)
    {
        $this->redis = ClientFactory::create([
            'server' => 'tcp://127.0.0.1:6379', // or 'unix:///tmp/redis.sock'
            'timeout' => 2
        ]);
//        $this->redis->set(__CLASS__, 12774);
        $this->page = $this->redis->get(__CLASS__);
        parent::__construct($urlRaw);
    }

    function getContentAndSaveToBody($url)
    {
        $this->body = $this->doRequest($url);
        return $this->body;
    }

    function doRequest($url = '', $postData = [])
    {
        return parent::doRequest($url, $postData); // TODO: Change the autogenerated stub
    }

    function hasNew()
    {
        // TODO:是否有新的内容
    }

    function savePerson($contentDom)
    {
//        $this->getEngineer($id);//for test
        $collection = $this->mongoConnection->build_info1->an_quan_ping_jia_shi;
        $trs = $contentDom->find("tr");
        $pairs = $this->trs2pair($trs);
        $personInfo = [];
        $personInfo['siteId'] = $this->page;
        foreach ($pairs as $pair) {
            if (strcmp($pair['name'], 'regTime') === 0) {
                $personInfo['startTime'] = $pair['value'][0];
                $personInfo['endTime'] = $pair['value'][1];
                continue;
            }
            if ($pair['name'] != '' && $pair['value'] != '') {
                $personInfo[($pair['name'])] = $pair['value'];
            }
        }
        $collection->insertOne($personInfo);
    }

    function trs2pair($trs)
    {
        $pairs = [];
        foreach ($trs as $tr) {
            $tds = $tr->children();
            if ($tds->length == 2 || $tds->length == 3) {
                $pairs[] = $this->chineseField2en($tds->eq(0)->text(), $tds->eq(1)->text());
            } elseif ($tds->length == 4 || $tds->length == 5) {
                $pairs[] = $this->chineseField2en($tds->eq(0)->text(), $tds->eq(1)->text());
                $pairs[] = $this->chineseField2en($tds->eq(2)->text(), $tds->eq(3)->text());
            } elseif ($tds->length == 6 || $tds->length == 7) {
                $pairs[] = $this->chineseField2en($tds->eq(0)->text(), $tds->eq(1)->text());
                $pairs[] = $this->chineseField2en($tds->eq(2)->text(), $tds->eq(3)->text());
            }
        }
        return $pairs;
    }

    function chineseField2en($chineseName, $value)
    {
        $map = [
            '姓名' => 'personName',
            '职业资格证书编号' => 'certNumber',
            '级别' => 'certLevel',
            '注册性质' => 'regType',
            '注册单位' => 'compName',
            '注册状态' => 'regState',
            '注册期' => 'regTime',
        ];
        $enName = $map[trim($chineseName)];
        $value = trim($value);
        switch ($enName) {
            case 'regTime':
                $timeStrs = explode('至', $value);
                $value = [];
                $timeStrs[0] = trim($timeStrs[0]);
                $timeStrs[1] = trim($timeStrs[1]);
                $value[0] = $this->strGetTime($timeStrs[0], true);
                if (strcmp($timeStrs[1], '无固定期') === 0) {
                    $value[1] = $this->strGetTime('2030-01-01', true);
                } else {
                    $value[1] = $this->strGetTime($timeStrs[1], true);
                }
                break;
        }
        return ['name' => $enName, 'value' => $value];
    }

    function strGetTime($timeStr, $first = true)
    {
        if (preg_match_all('/\d{4}-\d{2}-\d{2}/', $timeStr, $match)) {
            if ($first) {
                return strtotime($match[0][0]);
            }
            return strtotime(end($match[0]));
        }
        return 0;
    }


    function savePage()
    {
//        $this->saveCompany('7c6c6710-4ece-43c5-8013-5dc88dd4d273');// for test$collection = (new \MongoDB\Client('mongodb://localhost:27017'))->build_info1->an_quan_ping_jia_shi;
        $collection = $this->mongoConnection->build_info1->an_quan_ping_jia_shi;
        $personInDb = $collection->findOne(['siteId' => $this->page]);
        if (!empty($personInDb)) {
            echo "exist!\n";
            return false;
        }
        $this->getContentAndSaveToBody($this->url);
        $this->bodyQuery = \QueryPath::withHTML5($this->body);
        $this->content = $this->bodyQuery->find('table.conInfo');
        $this->savePerson($this->content);
        return true;
    }

    function moveToNext()
    {
        if ($this->page >= 40778) {
            return false;
        }
        $this->page = $this->redis->incr(__CLASS__);
        $this->url = str_replace('{page}', $this->page, $this->urlRaw);
        return true;
    }
}