<?php
/**
 * Created by PhpStorm.
 * User: wangyibo
 * Date: 2016-11-19
 * Time: 20:56
 */

namespace BuildInfo\crawler;

use RedisClient\RedisClient;
use RedisClient\ClientFactory;

class MohurdGovCnCompanyListCrawler extends BaseCrawler
{
    public $postData = [];
    public $bodyQuery;
    private static $mongoInstance;

    function __construct($urlRaw)
    {
        $this->redis = ClientFactory::create([
            'server' => 'tcp://127.0.0.1:6379', // or 'unix:///tmp/redis.sock'
            'timeout' => 2
        ]);
//        $this->redis->set(__CLASS__, 12774);
        $this->page = $this->redis->get(__CLASS__);
        if (!$this->page) {
            $this->redis->set(__CLASS__, 1);
            $this->page = 1;
        }
        $this->postData = $this->getPostData($this->page, 'QY_ZZ_ZZZD_001');
        parent::__construct($urlRaw);
    }

    function getContentAndSaveToBody($url)
    {
        $this->body = $this->doRequest($url, $this->postData);
//        print_r($this->postData);
        return $this->body;
    }

    function doRequest($url = '', $postData = [])
    {
        return parent::doRequest($url, $postData); // TODO: Change the autogenerated stub
    }

    function hasNew()
    {
        // TODO:是否有新的内容
    }

    function savePage()
    {
//        $res=$this->doRequest('http://115.29.113.202/addr.php');
//        print_r($res);exit;
//        $this->savePeople('000B0650-76EC-4594-85D4-862DFDCEE8A9');
        $collection = $this->mongoConnection->build_info1->jsb_company;
        $this->getContentAndSaveToBody($this->url);
        $this->bodyQuery = \QueryPath::withHTML5($this->body);
        $this->content = $this->bodyQuery->find('.cursorDefault');
        $trs = $this->content->find('tr');
        $results = [];
        $lines=0;
        foreach ($trs as $tr) {
            $lines++;
            $licenceNumber = trim($tr->find('td')->eq(1)->text());
            $a = $tr->find('td')->eq(2)->find('a');
            $compName = trim($a->text());
            $href = $a->attr('href');
            $pos = strrpos($href, '/');
            $zjbId = substr($href, $pos + 1);
//            echo $zjbId;exit;
            $compInfo = $collection->findOne(['compName' => $compName]);
            if (!empty($compInfo)) {
                echo "exist! " . $compName . "\n";
                $results[] = true;
                continue;
            }
            $result = $collection->insertOne(['zjbId' => $zjbId, 'licenceNumber' => $licenceNumber, 'compName' => $compName]);
            if ($result) {
                $results[] = true;
            }
        }
        echo "meet lines:" . $lines . "\n";
        if (!empty($results)) {
            return true;
        }
        return false;
    }

    function moveToNext()
    {
        if ($this->page >= 227) {
            return false;
        }
        $this->page = $this->redis->incr(__CLASS__);
        $this->url = str_replace('{
                page}', $this->page, $this->urlRaw);
        $this->postData = $this->getPostData($this->page, 'QY_ZZ_ZZZD_001');
        return true;
    }

    function getPostData($page, $qy_type)
    {
        $postData = [];
        $postData['$reload'] = '0';
//        $postData['qy_type'] = $qy_type;
        $postData['$pg'] = $page;
        $postData['$pgsz'] = '1000';
        return $postData;
    }

}