<?php
/**
 * Created by PhpStorm.
 * User: wangyibo
 * Date: 2016-11-19
 * Time: 20:56
 */

namespace BuildInfo\crawler;

use RedisClient\RedisClient;
use RedisClient\ClientFactory;

class SichuanJiaotongCreditCrawler extends BaseCrawler
{
    public $bodyQuery;
    public $page = 0;

    function getContentAndSaveToBody($url)
    {
        $this->body = iconv('gbk', 'utf-8', $this->doRequest($url));
        return $this->body;
    }

    function doRequest($url = '', $postData = [])
    {
        return parent::doRequest($url, $postData); // TODO: Change the autogenerated stub
    }

    function hasNew()
    {
        // TODO:是否有新的内容
    }

    function saveCompany($compInfo)
    {
//        $this->getEngineer($id);//for test
        $collection = (new \MongoDB\Client('mongodb://localhost:27017'))->build_info1->jiaotong_credit;
        try {
            $has = $collection->findOne(['compName' => $compInfo['compName']]);
            if (!$has) {
                $result = $collection->insertOne($compInfo);
            } else {
                $result = $collection->updateOne(
                    ['compName' => $compInfo['compName']],
                    ['$set' => $compInfo]
                );
            }
            if ($result) {
                return true;
            }
        } catch (\MongoDB\Driver\Exception\BulkWriteException $e) {
            return false;
        }
    }

    function savePage()
    {
//        $this->saveCompany('7c6c6710-4ece-43c5-8013-5dc88dd4d273');// for test
        $this->getContentAndSaveToBody($this->url);
        $this->bodyQuery = \QueryPath::withHTML5($this->body);
        $this->content = $this->bodyQuery->find('table')->eq(3);
        $trs = $this->content->find('tr');
        $lineNum = 0;
        foreach ($trs as $tr) {
            if (++$lineNum == 1) {
                continue;
            }
            $company = [];
            $company['compName'] = trim($tr->find('td')->eq(0)->find('a')->text());
            $company['industryType'] = trim($tr->find('td')->eq(1)->text());
            $company['businessType'] = trim($tr->find('td')->eq(2)->text());
            $company['level'] = trim($tr->find('td')->eq(4)->text());
            $compDetail = $this->saveCompany($company);
            $lines[] = $compDetail;
        }
        if (!empty($lines)) {
            return true;
        }
        return false;
    }

    function moveToNext()
    {
        $nextPageContent = $this->bodyQuery->find('.tr1')->text();
        if (preg_match('/下一页/', $nextPageContent)) {
            $this->page += 10;
            $this->url = str_replace('{page}', $this->page, $this->urlRaw);
            return true;
        } else {
            return false;
        }
    }
}