<?php
/**
 * Created by PhpStorm.
 * User: wangyibo
 * Date: 2016-11-19
 * Time: 20:56
 */

namespace BuildInfo\crawler;

use RedisClient\RedisClient;
use RedisClient\ClientFactory;

class ZhuCeAnQuanGongChengShiCrawler extends BaseCrawler
{
    public $bodyQuery;
    public $page = 0;
    protected $companyCollection;
    protected $limit = 1;

    function __construct($urlRaw)
    {
        $this->redis = ClientFactory::create([
            'server' => 'tcp://127.0.0.1:6379', // or 'unix:///tmp/redis.sock'
            'timeout' => 2
        ]);
        $this->page = $this->redis->get(__CLASS__);
        if (empty($this->page)) {
            $this->redis->set(__CLASS__, 0);
            $this->page = $this->redis->get(__CLASS__);
        }
        parent::__construct($urlRaw);
    }

    function getContentAndSaveToBody($url)
    {
        $this->body = iconv('gbk', 'utf-8', $this->doRequest($url));
        return $this->body;
    }

    function doRequest($url = '', $postData = [])
    {
        return parent::doRequest($url, $postData); // TODO: Change the autogenerated stub
    }

    function hasNew()
    {
        // TODO:是否有新的内容
    }

    function saveCompany($compInfo)
    {
        $collection = (new \MongoDB\Client('mongodb://localhost:27017'))->build_info1->an_quan_gong_cheng_shi;
        $document = $collection->findOne(['compName' => $compInfo['compName']]);
        if (!empty($document)) {
            echo "company exists!\n";
            return true;
        }
        $url = 'http://rmocse.chinasafety.ac.cn/UnitSearch.aspx?UnitsName=' . urlencode(iconv('utf-8', 'gbk', $compInfo['compName']));
        $this->getContentAndSaveToBody($url);
        $this->bodyQuery = \QueryPath::withHTML5($this->body);
        $trs = $this->bodyQuery->find('#ctl00_ContentPlaceHolder1_dlUnitsSearch')->find('table');
        $lineNum = 0;
        foreach ($trs as $tr) {
            if (++$lineNum < 3) {
                continue;
            }
            $engineer = [];
            $tds = $tr->find('td');
            $engineer['personName'] = trim($tds->eq(0)->text());
            $engineer['certNumber'] = trim($tds->eq(2)->text());
            $dateStr = trim($tds->eq(3)->text());
            $dateStr = preg_replace('/(年|月)/', '-', $dateStr);
            $dateStr = preg_replace('/日.*$/', '', $dateStr);
            $engineer['endTime'] = strtotime($dateStr);
            $engineer['regType'] = trim($tds->eq(4)->text());
            $engineer['compName'] = trim($tds->eq(5)->text());
            try {
                $result = $collection->insertOne($engineer);
            } catch (\MongoDB\Driver\Exception\BulkWriteException $e) {
                return false;
            }
        }
    }


    function savePage()
    {
//        $this->saveCompany('7c6c6710-4ece-43c5-8013-5dc88dd4d273');// for test
        $this->companyCollection = (new \MongoDB\Client('mongodb://localhost:27017'))->build_info1->company;
        $companies = $this->companyCollection->find([], [
            'limit' => $this->limit,
            'sort' => ['_id' => 1],
            'skip' => $this->page * $this->limit
        ]);
        foreach ($companies as $company) {
            $this->saveCompany($company);
        }
        return true;
    }

    function moveToNext()
    {
        if ($this->companyCollection->count() <= $this->limit * $this->page) {
            return false;
        }
        $this->page = $this->redis->incr(__CLASS__);
        return true;
    }
}